### ISSUE TITLE
Betterdiscord

### ISSUE THREAD

**Issue by Snowwy1337** [younesaassila/discord-status-countdown#5]
Should turn this into a better discord plugin for better stability, its randomly thinking the countdown has already finished

**Comment by younesaassila** [comment]
Anyone wanting to create a Better Discord plugin is free to do so. Could you please describe more precisely a situation in which the extension believes the countdown has ended when it hasn't? What browser are you using?

**Comment by younesaassila** [comment]
The issue is now fixed. Thanks for your report!
